#!/bin/bash

path=$HOME/.repos
repos=$(ls -1 $path)
edits=$'exit\n'
x=1
cd $path

for repo in $repos; do
    cd $repo
    echo $(pwd)
    echo "pre frist --porcelain"
    result=$(git status --porcelain)
    echo "after frist --porcelain"
    if [[ -n $result ]]; then
        edits+="$repo"
        edits+=$'\n'
    fi
    cd ..
done

echo $edits
printf "%s" "$edits"

until [[ "$edits" == "exit\n" || $x -eq 5 ]]; do
    edit=$(printf "%s" "$edits" | dmenu -c -l 10 )
    cd $edit
    if [[ "$edit" == "exit" || -z "$edit" ]]; then
        exit
    fi
    cd "$path/$edit" || continue
    commit_msg=$(git status --porcelain | dmenu -i -c -l 10 -p "$edit")
    if [[ -n "$commit_msg" ]]; then
        git add -A
        git commit -m "$commit_msg"
        git push
    fi

    edits=$(printf "%s" "$edits" | grep -vxF "$edit")
    (( x++ ))
done


