#!/bin/bash

path=$HOME/.repos
repos=$(ls -1 $path)
edits=$''
x=1
cd $path

for repo in $repos; do
    cd $repo
    # echo $(pwd)
    result=$(git status --porcelain)
    if [[ -n $result ]]; then
        edits+="$repo"
        edits+=$'\n'
    fi
    cd ..
done

if [[ "$edits" == "" ]]; then
    edits="no edits"
fi
# echo $edits
# printf "%s" "$edits"

# until [[ "$edits" == "exit\n" || $x -eq 15 ]]; do
until [[ "$edits" == "" ]]; do
    edit=$(printf "%s" "$edits" | dmenu -c -l 10 )
    cd $edit

    cd "$path/$edit" || continue
    commit_msg=$(git status --porcelain | dmenu -i -c -l 10 -p "$edit")
    if [[ -n "$commit_msg" ]]; then
        git add -A
        git commit -m "$commit_msg"
        git push
    fi

    edits=$(printf "%s" "$edits" | grep -vxF "$edit")
    (( x++ ))
done


